databases:
  - name: meo-database
    plan: free
    databaseName: meo_database
    user: meo_database_user

services:
  - type: web
    plan: free
    name: google_question
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn google_question.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: meo_database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4