# Generated by Django 3.2.25 on 2024-07-30 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QAS', '0002_auto_20240730_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(default='ご来店ありがとうございました。本日は満足していただけましたでしょうか', max_length=100)),
                ('very_satisfied_label', models.CharField(default='非常に満足', max_length=100)),
                ('satisfied_label', models.CharField(default='満足', max_length=100)),
                ('neutral_label', models.CharField(default='普通', max_length=100)),
                ('dissatisfied_label', models.CharField(default='不満', max_length=100)),
                ('very_dissatisfied_label', models.CharField(default='非常に不満', max_length=100)),
                ('very_satisfied_redirect_url', models.URLField(blank=True, null=True)),
                ('satisfied_redirect_url', models.URLField(blank=True, null=True)),
                ('neutral_redirect_url', models.URLField(blank=True, null=True)),
                ('dissatisfied_redirect_url', models.URLField(blank=True, null=True)),
                ('very_dissatisfied_redirect_url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='QAS.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
