# Generated by Django 3.2.25 on 2024-07-31 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QAS', '0006_alter_reviewsetting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
