# Generated by Django 3.2.25 on 2024-08-01 07:34

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAS', '0009_auto_20240801_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='星')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=100, verbose_name=django.contrib.auth.models.User)),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
