# Generated by Django 3.2.25 on 2024-08-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QAS', '0012_questionmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questionmodel',
        ),
    ]
