# Generated by Django 3.2.25 on 2024-08-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAS', '0014_improvesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvesetting',
            name='is_required1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='improvesetting',
            name='is_required2',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='improvesetting',
            name='is_required3',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='improvesetting',
            name='is_required4',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='improvesetting',
            name='is_required5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='improvesetting',
            name='question_text1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='improvesetting',
            name='question_text2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='improvesetting',
            name='question_text3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='improvesetting',
            name='question_text4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='improvesetting',
            name='question_text5',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
