# Generated by Django 3.2.25 on 2024-08-02 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QAS', '0015_auto_20240802_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImproveResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text1', models.CharField(blank=True, max_length=100)),
                ('question_text2', models.CharField(blank=True, max_length=100)),
                ('question_text3', models.CharField(blank=True, max_length=100)),
                ('question_text4', models.CharField(blank=True, max_length=100)),
                ('question_text5', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
