# Generated by Django 3.2.25 on 2024-08-02 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QAS', '0016_improveresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='improveresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
