# Generated by Django 3.2.25 on 2024-08-05 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QAS', '0017_improveresult_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvesetting',
            name='question_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='improveresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
