# Generated by Django 3.2.25 on 2024-08-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAS', '0018_auto_20240805_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='store_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
