# Generated by Django 3.2.25 on 2024-08-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAS', '0020_alter_improveresult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsetting',
            name='question_title',
            field=models.CharField(default='ご来店ありがとうございました。本日は満足していただけましたでしょうか？', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='google_review_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
