# Generated by Django 3.2.25 on 2024-08-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAS', '0021_auto_20240819_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='google_review_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
