# Generated by Django 3.2.25 on 2024-08-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAS', '0022_alter_userprofile_google_review_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='store_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
