# Generated by Django 3.2.25 on 2024-08-29 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QAS', '0023_userprofile_store_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text1', models.TextField(blank=True, max_length=1000)),
                ('response_text2', models.TextField(blank=True, max_length=1000)),
                ('response_text3', models.TextField(blank=True, max_length=1000)),
                ('response_text4', models.TextField(blank=True, max_length=1000)),
                ('response_text5', models.TextField(blank=True, max_length=1000)),
                ('filter_text1', models.CharField(blank=True, choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4')], max_length=50)),
                ('filter_text2', models.CharField(blank=True, choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4')], max_length=50)),
                ('filter_text3', models.CharField(blank=True, choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4')], max_length=50)),
                ('filter_text4', models.CharField(blank=True, choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4')], max_length=50)),
                ('filter_text5', models.CharField(blank=True, choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4')], max_length=50)),
                ('is_allswitch', models.BooleanField(blank=True, default=False)),
                ('is_auto1', models.BooleanField(blank=True, default=False)),
                ('is_auto2', models.BooleanField(blank=True, default=False)),
                ('is_auto3', models.BooleanField(blank=True, default=False)),
                ('is_auto4', models.BooleanField(blank=True, default=False)),
                ('is_auto5', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AiResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
