# Generated by Django 3.2.25 on 2024-08-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAS', '0024_airesponse_autoresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airesponse',
            name='response_text',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
