# Generated by Django 3.2.25 on 2024-08-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAS', '0025_alter_airesponse_response_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesponse',
            name='business_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='airesponse',
            name='match_language',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='airesponse',
            name='tone_level',
            field=models.IntegerField(choices=[(1, '丁寧'), (2, '普通'), (3, 'フランク')], default=2),
        ),
        migrations.AlterField(
            model_name='airesponse',
            name='response_text',
            field=models.TextField(blank=True),
        ),
    ]
