# Generated by Django 3.2.25 on 2024-08-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAS', '0026_auto_20240829_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoresponse',
            old_name='is_allswitch',
            new_name='is_auto',
        ),
        migrations.RenameField(
            model_name='autoresponse',
            old_name='response_text1',
            new_name='response_text',
        ),
        migrations.RemoveField(
            model_name='autoresponse',
            name='filter_text1',
        ),
        migrations.RemoveField(
            model_name='autoresponse',
            name='filter_text2',
        ),
        migrations.RemoveField(
            model_name='autoresponse',
            name='filter_text3',
        ),
        migrations.RemoveField(
            model_name='autoresponse',
            name='filter_text4',
        ),
        migrations.RemoveField(
            model_name='autoresponse',
            name='filter_text5',
        ),
        migrations.RemoveField(
            model_name='autoresponse',
            name='is_auto1',
        ),
        migrations.RemoveField(
            model_name='autoresponse',
            name='is_auto2',
        ),
        migrations.RemoveField(
            model_name='autoresponse',
            name='is_auto3',
        ),
        migrations.RemoveField(
            model_name='autoresponse',
            name='is_auto4',
        ),
        migrations.RemoveField(
            model_name='autoresponse',
            name='is_auto5',
        ),
        migrations.RemoveField(
            model_name='autoresponse',
            name='response_text2',
        ),
        migrations.RemoveField(
            model_name='autoresponse',
            name='response_text3',
        ),
        migrations.RemoveField(
            model_name='autoresponse',
            name='response_text4',
        ),
        migrations.RemoveField(
            model_name='autoresponse',
            name='response_text5',
        ),
        migrations.AddField(
            model_name='autoresponse',
            name='filter_text',
            field=models.CharField(blank=True, choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4'), ('option5', 'Option 5')], max_length=50),
        ),
        migrations.AddField(
            model_name='autoresponse',
            name='pattern_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
