# Generated by Django 3.2.25 on 2024-09-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAS', '0029_autoresponse_bool_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoresponse',
            name='bool_text',
            field=models.CharField(blank=True, choices=[('ontext', 'テキスト有り'), ('nottextテキスト無し', 'Nottext')], max_length=20),
        ),
        migrations.AlterField(
            model_name='autoresponse',
            name='filter_text',
            field=models.CharField(blank=True, choices=[('option5', '★5'), ('option4', '★4'), ('option3', '★3'), ('option2', '★2'), ('option1', '★1')], max_length=20),
        ),
    ]
