# Generated by Django 3.2.25 on 2024-09-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAS', '0030_auto_20240902_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoresponse',
            name='bool_text',
            field=models.CharField(blank=True, choices=[('ontext', 'テキスト有り'), ('nottext', 'テキスト無し')], max_length=20),
        ),
    ]
