# Generated by Django 3.2.25 on 2024-09-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAS', '0031_alter_autoresponse_bool_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoresponse',
            name='aitest',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
