# Generated by Django 3.2.25 on 2024-09-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAS', '0032_autoresponse_aitest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airesponse',
            name='tone_level',
            field=models.CharField(choices=[('丁寧', '丁寧'), ('普通', '普通'), ('フランク', 'フランク'), ('相手に合わせる', '相手に合わせる')], default='普通', max_length=20),
        ),
    ]
